- .github/workflows/github-page.yml
- .github/workflows/quality.yml
- docs/README.md
- index.html
- package-lock.json
- package.json
- scss/index.scss
- src/components/player/player.js
Restores pillarbox as the player of the demo application.
> feat: restore pillarbox

- src/index.js
- src/layout/header/core-demo-header-component.js
- src/layout/header/core-demo-header-component.scss
- src/layout/header/demo-header-component.js
- src/layout/header/demo-header-component.scss
- static/showcases/multi-player.html
- static/showcases/start-time.html
- static/showcases/static-showcase.scss
Introduces distinct headers for standalone the showcases:
- Refactored the existing header, creating two variants – one without navigation and another with navigation links.
- The styling of the standalone showcases has been adjusted to integrate with the new header element.
> chore(showcase): add dedicated header to showcases

- src/components/player/player.js
Avoids adding `type=undefined` as a query parameter if no type was passed when loading a source. This bug occurred when loading a url int the examples page.
This was preventing sharing a url when a media was loaded through this form.
- Omits adding the type as a query parameter if its not set.
> fix: undefined type in url

- package-lock.json
- package.json
- src/layout/content/showcase/showcase-page.js
- static/showcases/blocked-segment.html
- static/showcases/blocked-segment.scss
- static/showcases/chapters-showcase.scss
- static/showcases/chapters.html
- static/showcases/skip-credits.html
- static/showcases/skip-showcase.scss
- static/showcases/static-showcase.scss
Introduces new showcases for integrators to benefit from the inclusion of custom text tracks in the pillarbox player (see srgssr/pillarbox-web/pull/207).
The showcases cover the implementation of: handling blocked segments, displaying current chapters, and managing time intervals. Code examples with ample comments have been added to provide developers with technical insight on how to integrate these features. See some screenshots below.
> Whenever a blocked segment is skipped, shows a notification on the bottom right of the player.
> A card with information of the currently playing chapter is displayed above the control bar. 
> Once a time interval is reached, a skip button is displayed on the bottom right of the player.
> chore(showcase): showcases for custom text tracks handling

- src/layout/content/examples/load-media-form-component.js
- src/layout/content/examples/load-media-form-component.scss
- src/layout/content/showcase/showcase-component.js
- src/layout/content/showcase/showcase-component.scss
- src/theme/animations.scss
Resolves #2 by making each showcase's implementation section individually collapsible.
- Added a `visibility` icon from material icons as a visual cue next to each showcase section title.
- Modified the text to display "Show the implementation" when the section is collapsed and "Hide the implementation" when expanded.
- Added an animation to ease the visual feedback.
- Moves the growing and shrink animation from the `load-media-form-component` stylesheet to the theme's animation stylesheet. Added fading out for the shrinking animation to match its reverse and renamed it: `fade-out-shrink`.
| ![Expanded implementation section](https://github.com/SRGSSR/pillarbox-web-demo/assets/11271371/09edc1db-a717-427e-a1f2-66e9bccfd803) | ![Colapsed implementation …
> chore(showcase): make implementation section collapsible

- src/theme/animations.scss
To prevent the triggering of multiple `animationend` events, a fix has been implemented for combined animations such as: `fade-in-grow`, `fade-out-shrink` and `slide-up-fade-in`. Previously, an `animationend` event would be triggered for each individual animation, leading to unexpected behavior. 
- Added `infinite` iteration count in one of the animations, ensuring that only a single `animationend` event is triggered.
> fix: avoid triggering multiple animationend events

- src/layout/content/showcase/showcase-page.scss
- src/layout/header/demo-header-component.scss
Adds padding to the menu links and more space between showcase sections.
| Before | After |
| -------| ------|
| ![Before](https://github.com/SRGSSR/pillarbox-web-demo/assets/11271371/eb9f2e31-b830-483a-96b6-18151aa1e6ba) | ![After](https://github.com/SRGSSR/pillarbox-web-demo/assets/11271371/2ad87089-835a-4836-9d70-78b1c900dde0) |
> style: adjust menu and showcases presentation

- package.json
- src/components/player/player.js
- src/index.js
- src/layout/content/settings/settings-page.js
- src/layout/content/settings/settings-page.scss
- src/theme/theme.scss
- src/utils/il-provider.js
This feature enhances the demo application's configurability by allowing users to specify a custom data provider host via the settings page. This flexibility is crucial for adapting the application to different data sources and environments.
- **Data Provider Host Setting:** Introduced an input field on the settings page for changing the data provider host. This setting is propagated throughout the demo, affecting the player and integration layer callbacks (for the search and list views). The new setting is saved in local storage.
- Reduced specificity of the theme's input styles to simplify overriding the style.
- Applied `appearance: none` to select elements. In Safari browsers this hide default browser-specific appearances, which was showing up until now.
> feat(settings): add data provider host setting

- static/showcases/blocked-segment.html
- static/showcases/chapters.html
- static/showcases/skip-credits.html
Replaces the built-in text track events, specifically `cuechange`, with these custom events:
- `srgssr/chapter` for chapter changes.
- `srgssr/blocked-segment` to identify restricted content.
- `srgssr/interval` for detecting skippable content.
This change provides a more robust solution across various browsers, ensuring a more consistent user experience.
> fix(showcase): replace native text track events

- src/layout/header/demo-header-component.scss
Fixes the menu item wrapping by adjusting the margin between items and using a flex box on the parent element.
| Before | After |
|--------|-------|
| <img src="https://github.com/SRGSSR/pillarbox-web-demo/assets/11271371/09a3bce6-b82d-42f4-917c-6199f82c1aee" height="300"> | <img src="https://github.com/SRGSSR/pillarbox-web-demo/assets/11271371/e600ecee-86c2-4020-a8c2-69477cfd1e3b" height="300"> |
> fix(style): avoid menu items wrapping

- src/layout/content/examples/load-media-form-component.js
Resolves #29 by extracting the URN query parameter from PLAY URLs pasted into the main input on the example page. The application now initiates video playback using the extracted URN.
> chore: enable direct video playback from play urls

- index.html
- src/components/player/player.js
- src/layout/content/examples/load-media-form-component.js
- src/router/router.js
Media wasn't loading due to a typo in the properties for the key systems of a source.
- Converted `licenseUrl` and `certificateUrl` to `licenseUri` and `certificateUri` respectively.
- Added a condition to prevent multiple loading when the route changes but a player is already active.
> fix(example): loading media with drm

- index.html
- static/showcases/blocked-segment.html
- static/showcases/chapters.html
- static/showcases/multi-player.html
- static/showcases/skip-credits.html
- static/showcases/start-time.html
Removes the `crossorigin="anonymous"` attribute from the <video-js> tag because we were experiencing issues with cross-origin media.
> chore: remove crossorigin attribute from video-js tag

- package-lock.json
- package.json
- src/layout/content/showcase/showcase-page.js
- src/layout/content/showcase/showcase-page.scss
- static/showcases/blocked-segment.html
- static/showcases/blocked-segment.scss
- static/showcases/chapters-showcase.scss
- static/showcases/chapters.html
- static/showcases/playlist-showcase.scss
- static/showcases/playlist.html
- static/showcases/skip-credits.html
- static/showcases/skip-showcase.scss
Introduces a playlist example using the `@srgssr/pillarbox-playlist` plugin.
In the example player is configured with the playlist plugins, and showcases how to fetch the media data fetches media data for a set of predefined video sources, loading them into the player's playlist with metadata.
- Import a single stylesheet in the showcases to avoid vite optimisation to mixing the declared order of import.
> feat(showcase): add playlist example

- samples/angular/angular.json
- samples/angular/package-lock.json
- samples/angular/package.json
- samples/angular/src/app/app.config.ts
Fixes the StackBlitz workspace for the Angular sample by removing the `zone.js` polyfill. You can view the working StackBlitz for this branch [here](https://stackblitz.com/github/srgssr/pillarbox-web-demo/tree/fix/angular-sample/samples/angular).
- Upgraded Angular to version 18 to eliminate the dependency on `zone.js`. For more details, refer to the [Angular v18 release notes](https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe).
> fix: update angular sample for stackblitz compatibility

- docs/README.md
- public/404.html
Use custom domain urls throughout the documentation and  update redirect configuration for custom domain compatibility.
- Updated all URLs to the demo page to point to `demo.pillarbox.ch`
- Updated all API documentation URLs to point to `web.pillarbox.ch/api`
- Updated all URLs to the theme editor to point to `editor.pillarbox.ch`
- Updated all URLs to the web suite demo to point to `plugins.pillarbox.ch`
- Updated all URLs to the marketing page to point to `www.pillarbox.ch`
- Updated all URLs to the Android documentation page to point to `android.pillarbox.ch`
- Adjusted `pathSegmentsToKeep` to 0 in 404.html since we're now using a custom domain. This ensures URL paths are correctly redirected on GitHub Pages, preserving single-page app functionality without breaking the root path …
> chore: update urls for custom domain setup

- src/layout/content/showcase/showcase-page.js
- static/showcases/countdown.html
- static/showcases/countdown.scss
Resolves #47 by providing a code snippet to inspire a developer to create their own countdown component.
- add countdown to showcase page
- add html page and css containing countdown timer
> feat: add a countdown timer example to the demo

- src/layout/content/showcase/showcase-page.js
- static/showcases/chapter-selection.html
- static/showcases/chapter-selection.scss
Resolves #52 by providing a code snippet to inspire a developer to create their own chapter selection UI.
- add chapter selection to showcase page
- add html page and css containing chapter selection
> feat: add a chapter selection example to the demo

- src/layout/content/showcase/showcase-page.js
- static/showcases/firefox-pip.html
- static/showcases/firefox-pip.scss
Shows how to hide the PiP button on Firefox to meet certain use cases.
- Disables PiP via a configuration option
When disabled on the fly Firefox seems to have difficulty applying the change unless the browser is resized.
https://github.com/user-attachments/assets/49c5cf26-3625-40ae-8d34-7c558c5b114a
https://github.com/user-attachments/assets/57944c3c-8579-4a0c-a4ba-79785af0d405
> feat: add an example to hide the PiP button on Firefox

- src/layout/content/examples/examples.js
The current Telegiornale Flash example does not work anymore (a 404 is returned). This PR updates it with a new URN.
- Replace the non-working URN for Telegiornale Flash with a new URN.
> fix(example): replace Telegiornale Flash URN with a working one

- static/showcases/skip-credits.html
Change the default media of the skip-button demo for one that has the correct metadata.
> chore: change default urn for skip credits demo

- src/layout/content/showcase/showcase-page.js
This commit fixes a typo in the quality menu showcase.
> fix: typo in quality menu showcase

- static/showcases/blocked-segment.html
- static/showcases/chapter-selection.html
- static/showcases/chapters.html
- static/showcases/countdown.html
- static/showcases/playlist.html
- static/showcases/quality-menu.html
- static/showcases/skip-credits.html
- static/showcases/start-time.html
Resolves #68 by muting all showcases' content by default for a quieter testing experience.
> chore: mute all content by default

- package-lock.json
- package.json
- static/showcases/thumbnail-preview.html
This refactor is possible thanks to the new release of pillarbox-web, which exposes the `spriteSheet` property directly on `mediaData` and improves developer experience. There is no longer any need to check for chapters and then find the chapter by its URN to get the `spriteSheet`.
- update pillarbox-web to 1.24.0
- update showcase example
> refactor(thumbnail-preview): simplify access to spriteSheet property
